# Extended kalman Filter Solution

In [96]:
import numpy as np
from math import pi
from numpy.linalg import inv

# Initialization

In [97]:
F_k = np.array([[1,0.5],[0,1]])
G_k = np.array([[0,0.5]]).T
L_k = np.eye(2)*.1
X_k = np.array([[0,5]]).T
P_k = np.array([[0.01,0],[0,1]])
U = -2
S= 20
y1 = (pi/6)
D = 40
print(P_k)

[[0.01 0.  ]
 [0.   1.  ]]


# Prediction

In [98]:
x_k = F_k@X_k + G_k*(-2)
print('x_k')
print(x_k)
p_k = F_k@P_k@(F_k.T)+np.eye(2)@L_k@np.eye(2)
print('p_k')
print(p_k)
print(x_k)

x_k
[[2.5]
 [4. ]]
p_k
[[0.36 0.5 ]
 [0.5  1.1 ]]
[[2.5]
 [4. ]]


# Correction

In [99]:
H_k_1 =(S/((D-x_k[0])*(D-x_k[0])+S*S))
H_k = np.array([[H_k_1[0],0]])
k_1 = p_k@(H_k.T)@inv((H_k@p_k@H_k.T)+0.01)
print(k_1)

[[0.39686426]
 [0.55120036]]


In [100]:
F_x = x_k+(k_1@(y1-(H_k@x_k)))
print(F_x)
F_p = (1-k_1*H_k)*p_k
print(F_p)

[[2.69681178]
 [4.27334969]]
[[0.35841804 0.5       ]
 [0.49694837 1.1       ]]
